name: PR Policy

permissions:
  contents: read
  pull-requests: read
  statuses: write

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  require-linear:
    runs-on: ubuntu-latest
    steps:
      - uses: odigos-io/ci-core/require-linear@main

  release-note:
    runs-on: ubuntu-latest
    steps:
      - uses: odigos-io/ci-core/require-release-note@main
